### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by natasha-tullos** [wdi-atx-12/project-01#1]
We installed a petfinder api using npm and we are able to retrieve some data but it's difficult because we don't know the correct callback function that they require. We're on 16 if that helps??

**Comment by jhnsnc** [comment]
Which is the package you're having trouble with?

As a general suggestion, I would suggest creating a simple endpoint that attempts to retrieve data, add console logs in there to see what different variables contain, and use that to build an understanding of what the package is returning (modifying the console logs as needed).

**Comment by natasha-tullos** [comment]
https://www.npmjs.com/package/pet-finder-api

We are retrieving data, the issue is that we're only getting one dog, and we don't understand how to use the package to search the api.

**Comment by jhnsnc** [comment]
So you are able to retrieve data, but aren't sure about how to use the different methods/endpoints together to do what your app needs it to do?

It looks like the documentation for this package is pretty sparse. They're basically just pointing out which endpoints they support. However, they do mention that it's basically just a wrapper for the PetFinder API, so maybe we can come up with some good guesses about what the various options are by looking at the documentation for the main PetFinder API.

**Comment by jhnsnc** [comment]
I see on the [PetFinder API documentation](https://www.petfinder.com/developers/api-docs) that the `pet.find` endpoint allows a `location` option.

I bet that `pet.find` corresponds to the `findPet()` function from the `pet-finder-api` NPM package.

**Comment by jhnsnc** [comment]
(after taking a second look at the API:)
It might also make sense to simply identify the closest shelter(s) and then get a list of pets from the identified shelter(s).

Search functionality is notoriously difficult to implement, so don't worry if you have to start with filtering by specific properties (e.g. a dropdown for specifying breed, an input for minimum/maximum pet age, etc) rather than a single flexible "search" field.

**Comment by natasha-tullos** [comment]
We got doggos. Thank you for your doggo advice

**Comment by natasha-tullos** [comment]
Hey, so we have another issue going on

**Comment by natasha-tullos** [comment]
In our console log, when we console log the animals, we get all the dogs. When we use res.json though, we only get one dog that appears on our page.

**Comment by jhnsnc** [comment]
Sounds like you might be trying to send a response for each dog? If so, you would probably be seeing an error about trying to send multiple responses for one request (e.g. "cannot set headers after headers have been sent…")

Make sure you are only sending one response and that the response is the array of items you want to return. Sometimes you end up having to create your own array and prepare its contents manually before sending it. Other times you can basically just pass the response through to the front-end with minimal changes.

**Comment by natasha-tullos** [comment]
Can you be more specific about the array of items?

**Comment by jhnsnc** [comment]
That was me guessing about what your problem is. I'll need more detail to know exactly what to suggest.

It sounded to me like either you're trying to respond multiple times or you're not responding with the array you think you are. Either way, console logging should help clarify the problem.

**Comment by natasha-tullos** [comment]
Chris, yes. We are trying to obtain just dogs from a function that is predefined in petfinder. I cannot understand what you are trying to hint at. 

app.get('/', function(req, res) {
  petfinder.findPet(78721, {}, function(err, animals) {
    var result = [];
    animals.forEach(function(animal) {
      for(var prop in animal) {
        if(animal[prop] === 'Dog') {
          result.push({ animal: animal })
          console.log(result);
          res.write(result);

        }
      }
    })
  });
});

**Comment by natasha-tullos** [comment]
That is my issue. the forEach and the object for loop is the issue

**Comment by jhnsnc** [comment]
It looks like you're sending the response right after you find the first dog. You'll want to move the actual response down to after the loop has finished.
