### ISSUE TITLE
cannot redirect within routes.js

### ISSUE THREAD

**Issue by ludocracy** [wdi-atx-12/project-01#10]
expected behavior:

1. user clicks on add playlist
2. ajax posts new playlist to backend
3. backend redirects to new url
4. that route renders a different html file

observed behavior:
1. user clicks on add playlist
2. ajax posts correctly
nothing happens

**Comment by BritneyJo** [comment]
When it "posts correctly," that means it his hitting the correct route. From there, does the route call the correct function to render a new view? Let's see some of that code...

**Comment by jhnsnc** [comment]
Because an AJAX call is something the JavaScript in the client is doing, it will not be able to handle redirects. Perhaps the server could reply with the intended URL instead of sending an actual redirect?

Otherwise, perhaps we can Google something like "ajax redirects" and find an interesting solution to the problem.

**Comment by ludocracy** [comment]
sorry i don't have the code, karla does, but yes steps #3 and #4 are serverside.
we did test it and the redirect does hit the correct route and the route handler does console log as expected. it then should execute:
res.render('playlist')

**Comment by ludocracy** [comment]
playlist is an html file. we are not using EJS. we've also tried sendFile. we get no errors, but nothing happens

**Comment by jhnsnc** [comment]
If I understand it correctly, I believe what express does when you say `res.redirect('new_path');` is send a response with status `302` to the client, instructing it to find the intended response at the location `new_path`. I'm unsure about exactly how jQuery's AJAX function handles the initial `302` response.

I would bet you can understand what's happening better by looking at the AJAX request/response in the "Network" tab of your dev tools.

**Comment by ludocracy** [comment]
we've isolated the problem but can't find a solution in the docs. 
res.render expects a view. we are rendering a static file. but it refuses to find the html file.

**Comment by jhnsnc** [comment]
Resolution:

- keep CRUD / REST endpoints pure JSON, no redirects
- the `POST` request should respond with the newly created object
- on the front-end, the AJAX call should handle the `POST` response by looking for the ID and redirecting the browser accordingly
