### ISSUE TITLE
cannot retrieve string from text field (have WORKAROUND)

### ISSUE THREAD

**Issue by ludocracy** [wdi-atx-12/project-01#6]
https://github.com/ludocracy/project-01/blob/ajax-views/public/scripts/app.js

we have tried all combinations of the following:```
$('#playlistName').text()
$('#playlistName').value
$('#playlistName').innerText
```
and always get either an empty string or undefined. jquery otherwise works fine and the selector is indeed returning the correct DOM element.

however, this works fine:```
document.querySelector('#playlistName').value}

**Comment by jhnsnc** [comment]
I believe it's either `$(element).val()` or `$(element).get(0).value`. You can double-check the jQuery documentation.

I think `.val()` is the jQuery function and `$.get(0)` will get you the actual DOM element, so you can do the vanilla `.value`.
